// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_BURN)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_BURN_AOE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_INCINERATE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_LIGHTNING)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EFFECT_LIGHTNING_CHAIN)