;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Developer/BenH/Effects/DT_EffectGameplayTags.DT_EffectGameplayTags
+GameplayTagTableList=/Game/Developer/BenH/Quests/DT_QuestGameplayTags.DT_QuestGameplayTags
+GameplayTagTableList=/Game/Developer/BenH/Spells/DT_SpellGameplayTags.DT_SpellGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Enemy",DevComment="Enemy")
+GameplayTagList=(Tag="Character.Player",DevComment="Player")

